### ISSUE TITLE
unable to download jsbundle？？

### ISSUE THREAD

**Issue by aqnaruto** [wwayne/react-native-nba-app#21]
![image](https://cloud.githubusercontent.com/assets/9067159/18389725/cc636d5c-76d9-11e6-9d62-9c1c182f2dc0.png)

**Comment by shushiej** [comment]
I get the same error, is there a fix for this on android?

**Comment by svlapin** [comment]
Managed to get rid of this by typing `react-native start` after `react-native run-android`

**Comment by aqnaruto** [comment]
of course i did it ,but still not work.  does it is work on in your's environment @svlapin

**Comment by svlapin** [comment]
`react-native start` fixed the error you mentioned originally. After, I got the same as in #20 .
Fixed it by

``` diff
diff --git a/app/containers/App.js b/app/containers/App.js
index f0a863f..0765dac 100644
--- a/app/containers/App.js
+++ b/app/containers/App.js
@@ -18,7 +18,7 @@ import Game from './Game'
 import Player from './Player'
 import Team from './Team'

-export default class App extends Component {
+class App extends Component {

   constructor (props) {
     super(props)
```

Seems to work eventually.

**Comment by aqnaruto** [comment]
cool . thanks @svlapin

**Comment by America-first-melon** [comment]
Excuse me,
I have the same problem.
![qq 20170106104200](https://cloud.githubusercontent.com/assets/21686182/21705759/ce4c186e-d3fc-11e6-8631-296d525a718b.png)
and the app.js 
![qq 20170106104215](https://cloud.githubusercontent.com/assets/21686182/21705763/d76f8b92-d3fc-11e6-9f54-b0f8adff31fd.png)

**Comment by VincentZee** [comment]
when you run the command as usual：react-native run-android

you may see these info below：
Starting JS server...
Starting the packager in a new window is not supported on Windows yet.
Please start it manually using 'react-native start'.

so that lead you start the packager manually


you can also check if the packager has started by enter the url (http://localhost:8081/index.android.bundle?platform=android)

**Comment by aqnaruto** [comment]
thank you @VincentZee
